language: python
python:
 # - "2.6"
  - "2.7"
 # - "3.2"
 # - "3.3"
install:
  - pip install coveralls
# command to install dependencies
script: coverage run tests/test_simple.py
after_success:
  coveralls
branches:
  only:
    - master
