language: python
python:
 # - "2.6"
  - "2.7"
 # - "3.2"
 # - "3.3"
install:
  - pip install coveralls
  - pip install codecov
# command to install dependencies
script:
  - coverage run tests/test_simple.py

after_success:
  - coveralls
  - codecov
# branches:
#  only:
#    - master
